# Generated by Django 5.0.2 on 2024-02-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.staff'),
            preserve_default=False,
        ),
    ]
